name: Docker Release

on:
  push:
    branches: [master, main]

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract git commit SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Extract version from Cargo.toml
        id: version
        run: |
          version=$(grep '^version' ultrafast-mcp-sequential-thinking/Cargo.toml | head -1 | cut -d '"' -f2)
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ultrafast-mcp-sequential-thinking
          file: ./ultrafast-mcp-sequential-thinking/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ultrafast-mcp-sequential-thinking:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ultrafast-mcp-sequential-thinking:${{ steps.vars.outputs.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ultrafast-mcp-sequential-thinking:${{ steps.version.outputs.version }} 