name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Dry run cargo publish
        run: cargo publish --manifest-path ultrafast-mcp-sequential-thinking/Cargo.toml --dry-run
      # NOTE: To publish to GitHub Packages, ensure .cargo/config has a [registries.github] section.
      - name: Publish to GitHub Packages (ghcr.io)
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo publish --manifest-path ultrafast-mcp-sequential-thinking/Cargo.toml --registry github
      - name: Publish to crates.io (optional)
        if: env.CRATES_IO_TOKEN != null && env.CRATES_IO_TOKEN != ''
        env:
          CARGO_REGISTRY_TOKEN: ${{ env.CRATES_IO_TOKEN }}
        run: |
          cargo publish --manifest-path ultrafast-mcp-sequential-thinking/Cargo.toml 